name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-levels: 34
          build-tools: 34.0.0

      - name: Grant gradlew execute
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: udp-compass-apk
          path: app/build/outputs/apk/debug/*.apk
